# 开发环境配置
app:
  prefix: '/api'
  port: 8080
  logger:
    dir: './logs' # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
  # 文件相关
  file:
    location: './upload' # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    domain: 'http://localhost:8081' # 文件服务器地址，开发环境
    serveRoot: '/static' # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
# 数据库配置
db:
  mysql:
    host: '127.0.0.1'
    username: 'root'
    password: 'rootroot'
    database: 'clothsale'
    port: 3306
    charser: 'utf8mb4'
    logger: 'advanced-console'
    logging: false
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: false
